Repository kuzzleio/kuzzle-device-manager, pull requests merged in 2021-12, with the labels that each got.

#142 Use packaged kuzzle plugin commons
  lib/DeviceManagerPlugin.ts
  lib/core-classes/DeviceManagerEngine.ts
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#146 [breaking] Rename tenant event to engine event
  doc/1/guides/assets/index.md
  features/fixtures/application/app.ts
  lib/core-classes/PayloadService.ts
  package-lock.json
  package.json
Labels: changelog:enhancements

#148 Fix batch writter errors
  lib/core-classes/BatchProcessing/BatchController.ts
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#140 Feat/asset import csv
  doc/1/controllers/asset/import-assets/index.md
  features/AssetController.feature
  lib/DeviceManagerPlugin.ts
  lib/controllers/AssetController.ts
  lib/controllers/CRUDController.ts
  lib/core-classes/AssetService.ts
  lib/core-classes/DeviceService.ts
  lib/core-classes/index.ts
  lib/utils/writeMany.ts
Labels: changelog:new-features

#149 add provisioning event before and after
  doc/1/guides/provisioning/index.md
  features/Provisionning.feature
  features/fixtures/application/app.ts
  lib/core-classes/DeviceManagerEngine.ts
  lib/core-classes/DeviceService.ts
  lib/core-classes/PayloadService.ts
  package-lock.json
Labels: changelog:new-features
