Repository kuzzleio/kuzzle-device-manager, pull requests merged in 2022-08, with the labels that each got.

#194 Push multiple measures to multiple devices from a single payload
  .eslintrc.json
  features/AssetCategory.feature
  features/AssetController.feature
  features/Decoders.feature
  features/DeviceController/AttachEngine.feature
  features/DeviceController/Create.feature
  features/DeviceController/DetachEngine.feature
  features/DeviceController/LinkAsset.feature
  features/DeviceController/Misc.feature
  features/DeviceController/MultipleLink.feature
  features/DeviceController/UnlinkAsset.feature
  features/Engine.feature
  features/PayloadController.feature
  features/fixtures/application/app.ts
  features/fixtures/application/decoders/DummyMultiTempDecoder.ts
  features/fixtures/application/decoders/DummyTempDecoder.ts
  features/fixtures/application/decoders/DummyTempPositionDecoder.ts
  features/fixtures/application/decoders/index.ts
  features/fixtures/fixtures.js
  features/fixtures/payloads/dummy-multi-temp.js
  features/step_definitions/common/documents-steps.js
  features/support/hooks.js
  lib/DeviceManagerPlugin.ts
  lib/controllers/AssetController.ts
  lib/controllers/DecodersController.ts
  lib/controllers/DeviceController.ts
  lib/core-classes/AssetService.ts
  lib/core-classes/Decoder.ts
  lib/core-classes/DeviceService.ts
  lib/core-classes/MeasureService.ts
  lib/core-classes/PayloadService.ts
  lib/core-classes/index.ts
  lib/core-classes/registers/DecodersRegister.ts
  lib/mappings/assetsMappings.ts
  lib/mappings/deviceMappings.ts
  lib/mappings/index.ts
  lib/mappings/measuresMappings.ts
  lib/models/BaseAsset.ts
  lib/models/Device.ts
  lib/types/BaseAssetContent.ts
  lib/types/DecodedPayload.ts
  lib/types/DecoderContent.ts
  lib/types/DeviceContent.ts
  lib/types/DeviceManagerConfiguration.ts
  lib/types/Request.ts
  lib/types/measures/MeasureContent.ts
  lib/types/measures/MeasureDefinition.ts
Labels: changelog:breaking-changes, changelog:new-features

#206 2.0.0-rc8 : Allows to register measure with a value of same mappings
  lib/core-classes/AssetCategoryService.ts
  lib/core-classes/registers/MeasuresRegister.ts
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#207 Allow to enrich measure with asset info
  features/DeviceController/LinkAsset.feature
  features/PayloadController.feature
  features/fixtures/application/testPipes.ts
  lib/DeviceManagerPlugin.ts
  lib/core-classes/Decoder.ts
  lib/core-classes/MeasureService.ts
  lib/core-classes/PayloadService.ts
  lib/models/BaseAsset.ts
  lib/models/Device.ts
  lib/types/DecodedPayload.ts
  lib/types/measures/MeasureContent.ts
  package-lock.json
  package.json
Labels: changelog:enhancements

#212 Remove nested `origin` property from measure
  features/PayloadController.feature
  lib/mappings/measuresMappings.ts
Labels: changelog:enhancements
