Repository kuzzleio/kuzzle-device-manager, pull requests merged in 2022-09, with the labels that each got.

#211 Improve DX for Decoder class
  doc/1/controllers/decoder/list-decoders/index.md
  features/Decoders.feature
  features/DeviceController/Misc.feature
  features/fixtures/application/app.ts
  features/fixtures/application/decoders/DummyMultiTempDecoder.ts
  features/fixtures/application/decoders/DummyTempDecoder.ts
  features/fixtures/application/decoders/DummyTempPositionDecoder.ts
  lib/DeviceManagerPlugin.ts
  lib/controllers/AssetController.ts
  lib/controllers/DecoderController.ts
  lib/controllers/DeviceController.ts
  lib/controllers/index.ts
  lib/core-classes/AssetService.ts
  lib/core-classes/Decoder.ts
  lib/core-classes/DeviceService.ts
  lib/core-classes/MeasureService.ts
  lib/core-classes/PayloadService.ts
  lib/core-classes/registers/DecodersRegister.ts
  lib/measures/BatteryMeasure.ts
  lib/measures/HumidityMeasure.ts
  lib/measures/MovementMeasure.ts
  lib/measures/PositionMeasure.ts
  lib/measures/TemperatureMeasure.ts
  lib/models/BaseAsset.ts
  lib/types/DecodedPayload.ts
  lib/types/DecoderContent.ts
  lib/types/index.ts
  lib/types/measures/MeasureContent.ts
  lib/types/measures/MeasureDefinition.ts
Labels: changelog:enhancements

#217 Add code from the guide in the functional test application
  features/fixtures/application/app.ts
  features/fixtures/application/decoders/DummyAccelerometer3d.ts
  features/fixtures/application/decoders/index.ts
  features/fixtures/application/measures/Acceleration3dMeasure.ts
Labels: changelog:exclude

#218 Fix a possible null exception in `MeasureService.findAssetMeasureName`
  features/AssetCategory.feature
  features/DeviceController/LinkAsset.feature
  lib/core-classes/MeasureService.ts
Labels: changelog:bug-fixes

#220 Allow decode Device metadata
  features/AssetController.feature
  features/PayloadController.feature
  features/fixtures/application/app.ts
  features/fixtures/application/decoders/DummyTempDecoder.ts
  lib/DeviceManagerPlugin.ts
  lib/controllers/AssetController.ts
  lib/core-classes/MeasureService.ts
  lib/models/Device.ts
  lib/types/DecodedPayload.ts
  package-lock.json
  package.json
Labels: changelog:new-features
