Repository kuzzleio/kuzzle-device-manager, pull requests merged in 2023-03, with the labels that each got.

#273 Fix addition of asset context unlinked measures
  features/Device/Controller/AttachEngine.feature
  features/Device/Controller/GetMeasures.feature
  features/fixtures/application/decoders/DummyTempDecoder.ts
  lib/modules/measure/MeasureService.ts
  tests/helpers/index.ts
  tests/helpers/payloads.ts
  tests/helpers/setup.ts
  tests/modules/assets/action-get-measures.test.ts
  tests/modules/assets/asset-history.test.ts
  tests/modules/devices/action-attach-engine.test.ts
  tests/modules/devices/action-receive-measure.test.ts
  tests/modules/devices/action-scrud.test.ts
  tests/modules/ingestion-pipeline/before-ingestion.test.ts
  tests/modules/ingestion-pipeline/propagation.test.ts
  tests/scenario/dynamicaly-register-device-model.test.ts
Labels: changelog:bug-fixes

#271 Prevent empty link
  lib/modules/device/DevicesController.ts
  tests/modules/devices/link-unlink-asset.test.ts
Labels: changelog:bug-fixes

#278 Fix roles for IoT console v3
  lib/modules/asset/roles/RoleAssetsAdmin.ts
  lib/modules/asset/roles/RoleAssetsReader.ts
  lib/modules/device/roles/RoleDevicesAdmin.ts
  lib/modules/device/roles/RoleDevicesReader.ts
Labels: changelog:enhancements

#279 Allows to replace the device link with new measures
  doc/2/controllers/devices/linkAsset/index.md
  lib/modules/device/DeviceService.ts
  tests/helpers/document.ts
  tests/scenario/modules/devices/action-link-asset.test.ts
Labels: changelog:enhancements

#284 Clean module architecture
  index.ts
  lib/core/exports.ts
  lib/core/index.ts
  lib/modules/asset/AssetHistoryService.ts
  lib/modules/asset/AssetService.ts
  lib/modules/decoder/DecodersController.ts
  lib/modules/decoder/DecodersRegister.ts
  lib/modules/decoder/PayloadService.ts
  lib/modules/decoder/PayloadsController.ts
  lib/modules/decoder/index.ts
  lib/modules/device/DeviceService.ts
  lib/modules/measure/MeasureService.ts
  lib/modules/model/ModelService.ts
  lib/modules/model/ModelsRegister.ts
  lib/modules/model/index.ts
  lib/modules/plugin/DeviceManagerEngine.ts
  lib/modules/plugin/DeviceManagerPlugin.ts
  lib/modules/plugin/exports.ts
  lib/modules/plugin/index.ts
  lib/modules/plugin/types/DeviceManagerConfiguration.ts
  lib/modules/plugin/types/InternalCollection.ts
  lib/modules/shared/Module.ts
Labels: changelog:exclude

#283 Store reason of discarded payloads
  doc/2/concepts/measures-ingestion/index.md
  lib/modules/decoder/DecodingState.ts
  lib/modules/decoder/PayloadService.ts
  lib/modules/decoder/SkipError.ts
  lib/modules/decoder/collections/payloadsMappings.ts
  tests/scenario/migrated/decoder-payload-controller.test.ts
Labels: changelog:enhancements

#286 ModelService upsert -> createOrReplace
  lib/modules/model/ModelService.ts
  tests/scenario/migrated/model-controller.test.ts
  tests/scenario/modules/models/model-controller.test.ts
Labels: changelog:bug-fixes, module-model

#288 Full path nested metadata when create/update assets
  lib/modules/asset/AssetService.ts
  lib/modules/asset/types/AssetHistoryContent.ts
  tests/scenario/modules/assets/asset-history.test.ts
Labels: changelog:bug-fixes, module-asset
