Repository kuzzleio/kuzzle-device-manager, pull requests merged in 2023-04, with the labels that each got.

#287 Update metadata in existing assets when the model is modified
  lib/modules/asset/AssetService.ts
  lib/modules/asset/types/AssetEvents.ts
  lib/modules/model/ModelService.ts
  lib/modules/plugin/DeviceManagerEngine.ts
  package-lock.json
  package.json
  tests/scenario/modules/models/asset-model-metadata-propagation.test.ts
Labels: changelog:enhancements, module-model

#294 Fix search result type in AssetService
  lib/modules/asset/AssetService.ts
  package-lock.json
  package.json
Labels: changelog:exclude, module-asset

#293 Allow JSONObject in metadata
  lib/modules/shared/types/Metadata.ts
Labels: changelog:enhancements

#295 Export default mappings
  lib/modules/asset/collections/assetsHistoryMappings.ts
  lib/modules/asset/collections/assetsMappings.ts
  lib/modules/asset/exports.ts
  lib/modules/device/collections/deviceMappings.ts
  lib/modules/device/exports.ts
  lib/modules/measure/collections/measuresMappings.ts
  lib/modules/measure/exports.ts
  lib/modules/model/collections/modelsMappings.ts
Labels: changelog:enhancements

#291 Add type of measure linked in each links of asset measures.
  lib/modules/asset/collections/assetsMappings.ts
  lib/modules/asset/types/AssetContent.ts
  lib/modules/device/DeviceService.ts
  tests/scenario/migrated/asset-history.test.ts
  tests/scenario/modules/devices/action-link-asset.test.ts
  tests/tsconfig.json
Labels: changelog:new-features, module-measures

#298 Handle uninitialized measure in historization
  lib/modules/measure/MeasureService.ts
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#301 Add `persist:before` event to the ingestion pipeline
  doc/2/concepts/measures-ingestion/index.md
  lib/modules/measure/MeasureService.ts
  lib/modules/measure/types/MeasureEvents.ts
  package-lock.json
  package.json
  tests/application/tests/pipes.ts
  tests/scenario/modules/ingestion-pipeline/pipeline-persist-before.test.ts
  tests/scenario/modules/ingestion-pipeline/pipeline-process-before.test.ts
Labels: changelog:enhancements
